# Generated by Django 5.2 on 2025-07-11 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='fecha_fundación',
            new_name='fecha_fundacion',
        ),
    ]
