# Generated by Django 5.2 on 2025-12-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.CharField(blank=True, choices=[('afiliado', 'Afiliado'), ('externo', 'Externo')], max_length=20, null=True),
        ),
    ]
