# Generated by Django 5.2 on 2025-05-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id_correspondencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('paginas', models.IntegerField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_revision', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocEntrante',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('nro_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.CreateModel(
            name='DocInterno',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('gestion', models.PositiveIntegerField(default=2025, editable=False)),
                ('cite', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.CreateModel(
            name='DocSaliente',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('cite', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('archivo_word', models.FileField(blank=True, null=True, upload_to='documentos_borrador/')),
            ],
            bases=('correspondencia.correspondencia',),
        ),
    ]
