# Generated by Django 5.2 on 2025-07-07 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id_correspondencia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('paginas', models.IntegerField(default=1)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado')], max_length=20)),
                ('estado_actual', models.CharField(default='REGISTRADO', help_text='Último estado del documento (Ej: Derivado, En proceso, Archivado, Finalizado)', max_length=50)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última acción o modificación registrada')),
                ('activo', models.BooleanField(default=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaElaborada',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('cite', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('archivo_word', models.FileField(blank=True, null=True, upload_to='documentos_borrador/')),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.CreateModel(
            name='Interna',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('gestion', models.PositiveIntegerField(default=2025, editable=False)),
                ('cite', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.CreateModel(
            name='Recibida',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('nro_registro', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_recepcion', models.DateField()),
                ('hora_recepcion', models.TimeField()),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('hora_respuesta', models.TimeField(blank=True, null=True)),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.CreateModel(
            name='AccionCorrespondencia',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='correspondencia.correspondencia')),
            ],
        ),
    ]
