# Generated by Django 5.2 on 2025-11-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Plantilla para generación del documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias', to='documento.plantilladocumento'),
        ),
    ]
