# Generated by Django 5.2 on 2025-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibida',
            name='fecha_recepcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
