# Generated by Django 5.2.8 on 2025-11-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '0001_initial'),
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Plantilla para generación del documento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondencias', to='documento.plantilladocumento'),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, help_text='Nota recibida a la que responde esta nota elaborada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correspondencia.recibida'),
        ),
    ]
