# Generated by Django 5.2 on 2025-11-06 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
        ('documento', '0003_documento_contenido_extraido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accioncorrespondencia',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.RenameField(
            model_name='accioncorrespondencia',
            old_name='observacion',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='accioncorrespondencia',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='accioncorrespondencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='correspondencia',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='enviada',
            name='archivo_word',
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='estado_resultante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='fecha_modificación',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='fecha_visto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_destino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='usuario_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_origen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='estado_actual',
            field=models.CharField(default='REGISTRADO', help_text='Último estado del documento (Ej: Derivado, En proceso, Archivado, Finalizado)', max_length=50),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última acción o modificación registrada'),
        ),
        migrations.AddField(
            model_name='enviada',
            name='hora_envio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviada',
            name='hora_recepcion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibida',
            name='hora_recepcion',
            field=models.TimeField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibida',
            name='hora_respuesta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accioncorrespondencia',
            name='accion',
            field=models.CharField(choices=[('derivado', 'Derivado'), ('observado', 'Observado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto'), ('archivado', 'Archivado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='paginas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enviada',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviada',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='fecha_recepcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CorrespondenciaElaborada',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('sigla', models.CharField(default='FSTL-FTA', max_length=50)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('gestion', models.PositiveIntegerField(default=2025, editable=False)),
                ('cite', models.CharField(blank=True, max_length=100, unique=True)),
                ('contenido_html', models.TextField(blank=True, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('hora_envio', models.TimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('hora_recepcion', models.TimeField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_elaboracion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_introduccion', models.TextField(blank=True, null=True)),
                ('descripcion_desarrollo', models.TextField(blank=True, null=True)),
                ('descripcion_conclusion', models.TextField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(blank=True, help_text='Plantilla para generación del documento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondencias', to='documento.plantilladocumento')),
                ('respuesta_a', models.ForeignKey(blank=True, help_text='Nota recibida a la que responde esta nota elaborada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correspondencia.recibida')),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.DeleteModel(
            name='Interna',
        ),
    ]
