# Generated by Django 5.2 on 2025-11-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_correspondenciaelaborada_plantilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accioncorrespondencia',
            old_name='fecha_modificación',
            new_name='fecha_modificacion',
        ),
    ]
