# Generated by Django 5.2.8 on 2025-12-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_correspondenciaelaborada_plantilla'),
        ('correspondencia', '0002_initial'),
    ]

    operations = [
    ]
