# Generated by Django 5.2 on 2025-07-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_alter_recibida_fecha_recepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviada',
            name='archivo_word',
        ),
        migrations.AddField(
            model_name='interna',
            name='archivo_word',
            field=models.FileField(blank=True, null=True, upload_to='documentos_borrador/'),
        ),
    ]
