# Generated by Django 5.2 on 2025-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_correspondencia_contacto_correspondencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='docentrante',
            name='nro_registro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
