# Generated by Django 5.2 on 2025-07-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_remove_enviada_archivo_word_interna_archivo_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interna',
        ),
    ]
