# Generated by Django 5.2.8 on 2025-12-13 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_merge_20251213_1855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviada',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('cite', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('hora_envio', models.TimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('hora_recepcion', models.TimeField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.AlterModelOptions(
            name='accioncorrespondencia',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='correspondencia',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.RenameField(
            model_name='accioncorrespondencia',
            old_name='observacion',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='accioncorrespondencia',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='accioncorrespondencia',
            name='id_accion',
        ),
        migrations.RemoveField(
            model_name='accioncorrespondencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='correspondenciaelaborada',
            name='archivo_word',
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='estado_resultante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='fecha_visto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_destino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='usuario_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_origen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='contenido_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='descripcion_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='descripcion_desarrollo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='descripcion_introduccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='fecha_elaboracion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='gestion',
            field=models.PositiveIntegerField(default=2025, editable=False),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='hora_envio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='hora_recepcion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='numero',
            field=models.PositiveIntegerField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='sigla',
            field=models.CharField(default='FSTL-FTA', max_length=50),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accioncorrespondencia',
            name='accion',
            field=models.CharField(choices=[('derivado', 'Derivado'), ('observado', 'Observado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto'), ('archivado', 'Archivado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='cite',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Interna',
        ),
    ]
