# Generated by Django 5.2 on 2025-12-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_rename_fecha_modificación_accioncorrespondencia_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondencia',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AddField(
            model_name='enviada',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('devuelto', 'Devuelto'), ('rechazado', 'Rechazado'), ('extraviado', 'Extraviado'), ('direccion_incorrecta', 'Dirección incorrecta'), ('destinatario_incorrecto', 'Destinatario incorrecto')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='enviada',
            name='fecha_intento_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviada',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviada',
            name='numero_intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
