# Generated by Django 5.2 on 2025-12-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_alter_correspondencia_options_enviada_estado_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviada',
            name='estado_entrega',
        ),
        migrations.RemoveField(
            model_name='enviada',
            name='fecha_intento_entrega',
        ),
        migrations.RemoveField(
            model_name='enviada',
            name='motivo_no_entrega',
        ),
        migrations.RemoveField(
            model_name='enviada',
            name='numero_intentos',
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('devuelto', 'Devuelto'), ('rechazado', 'Rechazado'), ('extraviado', 'Extraviado'), ('direccion_incorrecta', 'Dirección incorrecta'), ('destinatario_incorrecto', 'Destinatario incorrecto')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='fecha_intento_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='motivo_no_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='numero_intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
