# Generated by Django 5.2 on 2025-07-14 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_delete_interna'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenciaElaborada',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='correspondencia.correspondencia')),
                ('tipo_documento', models.CharField(choices=[('comunicado', 'Comunicado'), ('convocatoria', 'Convocatoria'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('memorando', 'Memorando'), ('nota_interna', 'Nota Interna'), ('nota_externa', 'Nota Externa')], max_length=50)),
                ('sigla', models.CharField(default='FSTL-FTA', max_length=50)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('gestion', models.PositiveIntegerField(default=2025, editable=False)),
                ('cite', models.CharField(blank=True, max_length=100, unique=True)),
                ('asunto', models.CharField(max_length=255)),
                ('archivo_word', models.FileField(blank=True, null=True, upload_to='documentos_borrador/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos_final/')),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            bases=('correspondencia.correspondencia',),
        ),
    ]
