# Generated by Django 5.2 on 2025-07-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0005_correspondenciaelaborada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciaelaborada',
            name='asunto',
        ),
    ]
