# Generated by Django 5.2 on 2025-12-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0005_remove_enviada_estado_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciaelaborada',
            name='hora_envio',
        ),
        migrations.RemoveField(
            model_name='correspondenciaelaborada',
            name='hora_recepcion',
        ),
        migrations.RemoveField(
            model_name='enviada',
            name='hora_envio',
        ),
        migrations.RemoveField(
            model_name='enviada',
            name='hora_recepcion',
        ),
        migrations.RemoveField(
            model_name='recibida',
            name='hora_recepcion',
        ),
        migrations.RemoveField(
            model_name='recibida',
            name='hora_respuesta',
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviada',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviada',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='fecha_recepcion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
