# Generated by Django 5.2 on 2025-12-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0006_remove_correspondenciaelaborada_hora_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='ambito',
            field=models.CharField(blank=True, choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=20, null=True),
        ),
    ]
