# Generated by Django 5.2 on 2025-07-14 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0006_remove_correspondenciaelaborada_asunto'),
        ('documento', '0002_alter_plantilladocumento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciaelaborada',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='correspondenciaelaborada',
            name='archivo_word',
        ),
        migrations.RemoveField(
            model_name='correspondenciaelaborada',
            name='tipo_documento',
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='contenido_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Plantilla para generación del documento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondencias', to='documento.plantilladocumento'),
        ),
    ]
