# Generated by Django 5.2 on 2025-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0007_remove_correspondenciaelaborada_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='fecha_elaboracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
