# Generated by Django 5.2 on 2025-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0008_correspondenciaelaborada_fecha_elaboracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='fecha_elaboracion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
