# Generated by Django 5.2 on 2026-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0008_correspondenciaelaborada_destino_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='gestion',
            field=models.PositiveIntegerField(default=2026, editable=False),
        ),
    ]
