# Generated by Django 5.2 on 2025-07-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0009_alter_correspondenciaelaborada_fecha_elaboracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='paginas',
            field=models.IntegerField(default=1),
        ),
    ]
