# Generated by Django 5.2 on 2026-01-11 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0009_alter_correspondenciaelaborada_gestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibida',
            name='nro_registro',
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_registro', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('firmado', models.BooleanField(default=False)),
                ('usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recibida',
            name='recepcion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correspondencia', to='correspondencia.recepcion'),
        ),
    ]
