# Generated by Django 5.2 on 2025-07-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0010_alter_correspondencia_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='fecha_seguimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado')], max_length=20),
        ),
    ]
