# Generated by Django 5.2 on 2026-01-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0010_remove_recibida_nro_registro_recepcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibida',
            name='recepcion',
        ),
        migrations.AddField(
            model_name='recibida',
            name='nro_registro',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Recepcion',
        ),
    ]
