# Generated by Django 5.2 on 2025-07-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0011_correspondenciaelaborada_fecha_recepcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, help_text='Nota recibida a la que responde esta nota elaborada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correspondencia.recibida'),
        ),
    ]
