# Generated by Django 5.2 on 2025-07-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0012_correspondenciaelaborada_respuesta_a'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accioncorrespondencia',
            options={'ordering': ['fecha']},
        ),
        migrations.RenameField(
            model_name='accioncorrespondencia',
            old_name='observacion',
            new_name='comentario',
        ),
        migrations.AlterField(
            model_name='accioncorrespondencia',
            name='accion',
            field=models.CharField(choices=[('DERIVADO', 'Derivado'), ('VISTO', 'Visto'), ('OBSERVADO', 'Observado'), ('APROBADO', 'Aprobado')], max_length=50),
        ),
    ]
