# Generated by Django 5.2 on 2026-02-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0012_presellorecibida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('archivado', 'Archivado'), ('derivado', 'Derivado'), ('observado', 'Observado'), ('devuelto', 'Devuelto')], max_length=20),
        ),
    ]
