# Generated by Django 5.2 on 2026-02-10 16:45

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0013_alter_correspondencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='vector_embedding_html',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
