# Generated by Django 5.2 on 2026-02-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0014_correspondenciaelaborada_vector_embedding_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accioncorrespondencia',
            name='accion',
            field=models.CharField(choices=[('derivado', 'Derivado'), ('observado', 'Observado'), ('respondido', 'Respondido'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto'), ('archivado', 'Archivado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, help_text='Documento al que responde esta nota elaborada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='correspondencia.correspondencia'),
        ),
    ]
