# Generated by Django 5.2 on 2025-08-04 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0014_accioncorrespondencia_usuario_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='hora_envio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='hora_recepcion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviada',
            name='hora_envio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviada',
            name='hora_recepcion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibida',
            name='hora_recepcion',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibida',
            name='hora_respuesta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviada',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviada',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='fecha_recepcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
