# Generated by Django 5.2 on 2025-08-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0015_correspondenciaelaborada_hora_envio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
