# Generated by Django 5.2 on 2026-02-11 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0015_alter_accioncorrespondencia_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibida',
            name='relacionada_a',
            field=models.ForeignKey(blank=True, help_text='Documento previo con el que esta nota recibida se relaciona', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibidas_relacionadas', to='correspondencia.correspondencia'),
        ),
    ]
