# Generated by Django 5.2 on 2026-05-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0016_recibida_relacionada_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='descripcion_conclusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='descripcion_desarrollo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='descripcion_introduccion',
            field=models.TextField(),
        ),
    ]
