# Generated by Django 5.2 on 2026-05-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0017_alter_correspondenciaelaborada_descripcion_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='descripcion_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='descripcion_desarrollo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='descripcion_introduccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
