# Generated by Django 5.2 on 2025-08-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0017_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
