# Generated by Django 5.2 on 2025-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0018_accioncorrespondencia_visto_delete_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='descripcion_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='descripcion_desarrollo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondenciaelaborada',
            name='descripcion_introduccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
