# Generated by Django 5.2 on 2026-05-02 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0018_alter_correspondenciaelaborada_descripcion_conclusion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('respuesta_pendiente', 'Respuesta Pendiente'), ('respuesta_vencida', 'Respuesta Vencida'), ('seguimiento_pendiente', 'Seguimiento Pendiente'), ('seguimiento_vencido', 'Seguimiento Vencido')], max_length=25)),
                ('nivel_alerta', models.CharField(choices=[('preventiva', 'Preventiva'), ('critica', 'Crítica')], max_length=10)),
                ('fecha_vencimiento', models.DateTimeField(help_text='Fecha límite para respuesta/seguimiento')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('vista', models.BooleanField(default=False)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='correspondencia.correspondencia')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_alerta'],
                'indexes': [models.Index(fields=['usuario_responsable', 'activa', 'vista'], name='corresponde_usuario_40a56f_idx'), models.Index(fields=['fecha_vencimiento'], name='corresponde_fecha_v_1f7531_idx')],
            },
        ),
    ]
