# Generated by Django 5.2 on 2025-10-28 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0019_correspondenciaelaborada_descripcion_conclusion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVisualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visualizacion', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('notificacion', 'Desde notificación'), ('detalle', 'Desde vista de detalle'), ('otro', 'Otro origen')], default='detalle', max_length=50)),
                ('accion', models.CharField(default='Vista', max_length=100)),
                ('accion_correspondencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='correspondencia.accioncorrespondencia')),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia.correspondencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_visualizacion'],
            },
        ),
    ]
