# Generated by Django 5.2 on 2026-05-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0019_alertavencimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertaVencimiento',
        ),
    ]
