# Generated by Django 5.2 on 2025-10-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0020_historialvisualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='accioncorrespondencia',
            name='estado_resultante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='estado_actual',
            field=models.CharField(default='REGISTRADO', help_text='Último estado del documento (Ej: Derivado, En proceso, Archivado, Finalizado)', max_length=50),
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última acción o modificación registrada'),
        ),
    ]
