# Generated by Django 5.2 on 2026-05-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0020_delete_alertavencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presellorecibida',
            name='pre_nro_registro',
        ),
        migrations.AddField(
            model_name='presellorecibida',
            name='correspondencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_sello', to='correspondencia.recibida'),
        ),
        migrations.AddField(
            model_name='presellorecibida',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='presellorecibida',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
