# Generated by Django 5.2 on 2026-06-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0022_idempotencykey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idempotencykey',
            old_name='corrrespondencia_id',
            new_name='correspondencia_id',
        ),
    ]
