# Generated by Django 5.2 on 2026-06-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0023_rename_corrrespondencia_id_idempotencykey_correspondencia_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idempotencykey',
            table='idempotency_key',
        ),
    ]
