# Generated by Django 5.2 on 2026-06-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0024_alter_idempotencykey_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdempotencyKey',
        ),
    ]
