# Generated by Django 5.2 on 2026-06-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0025_delete_idempotencykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presellorecibida',
            name='correspondencia',
        ),
        migrations.RemoveField(
            model_name='presellorecibida',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='presellorecibida',
            name='numero',
        ),
        migrations.AddField(
            model_name='presellorecibida',
            name='pre_nro_registro',
            field=models.CharField(default='Reg-000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accioncorrespondencia',
            name='estado_resultante',
            field=models.CharField(blank=True, choices=[('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto'), ('archivado', 'Archivado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('archivado', 'Archivado'), ('devuelto', 'Devuelto')], max_length=20),
        ),
    ]
