# Generated by Django 5.2 on 2026-06-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0026_remove_presellorecibida_correspondencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='estado_actual',
        ),
        migrations.AlterField(
            model_name='accioncorrespondencia',
            name='estado_resultante',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('archivado', 'Archivado'), ('devuelto', 'Devuelto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('archivado', 'Archivado'), ('devuelto', 'Devuelto')], default='borrador', max_length=20),
        ),
    ]
