# Generated by Django 5.2 on 2026-06-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0027_remove_correspondencia_estado_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presellorecibida',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('usado', 'Usado'), ('anulado', 'Anulado')], db_index=True, default='disponible', max_length=15),
        ),
        migrations.AddField(
            model_name='presellorecibida',
            name='numero_correlativo',
            field=models.PositiveIntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibida',
            name='numero_correlativo',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recibida',
            name='pre_sello',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recibida', to='correspondencia.presellorecibida'),
        ),
        migrations.AlterField(
            model_name='accioncorrespondencia',
            name='estado_resultante',
            field=models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('archivado', 'Archivado'), ('devuelto', 'Devuelto'), ('entregado', 'Entregado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('enviado', 'Enviado'), ('archivado', 'Archivado'), ('devuelto', 'Devuelto'), ('entregado', 'Entregado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='estado_entrega',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('no_entregado', 'No entregado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='presellorecibida',
            name='pre_nro_registro',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='nro_registro',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
