# Generated by Django 5.2 on 2026-07-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0028_presellorecibida_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciaelaborada',
            name='estado_entrega',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('no_entregado', 'No entregado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='recibida',
            name='numero_correlativo',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
