# Generated by Django 5.2 on 2025-07-07 03:21

import django.db.models.deletion
import documento.models
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plantilla', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estructura_html', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('carta', 'Carta'), ('comunicado', 'Comunicado'), ('informe', 'Informe'), ('convocatoria', 'Convocatoria'), ('otro', 'Otro')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=documento.models.ruta_archivo)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('vector_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='correspondencia.correspondencia')),
            ],
        ),
    ]
