# Generated by Django 5.2 on 2025-05-04 17:05

import django.contrib.postgres.fields
import django.db.models.deletion
import documento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoInterno',
            fields=[
                ('id_tipo_documento_interno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento_interno', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=documento.models.ruta_archivo)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='correspondencia.correspondencia')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documento.tipodocumento')),
                ('tipo_documento_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_internos', to='documento.tipodocumentointerno')),
            ],
        ),
        migrations.CreateModel(
            name='vectorDocumento',
            fields=[
                ('id_vector', models.AutoField(primary_key=True, serialize=False)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vectores', to='documento.documento')),
            ],
        ),
    ]
