# Generated by Django 5.2 on 2025-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ambito',
            field=models.CharField(blank=True, choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=20, null=True),
        ),
    ]
