# Generated by Django 5.2 on 2025-07-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilladocumento',
            name='tipo',
            field=models.CharField(choices=[('comunicado', 'Comunicado'), ('convocatoria', 'Convocatoria'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('memorando', 'Memorando'), ('nota_interna', 'Nota Interna'), ('nota_externa', 'Nota Externa')], max_length=50),
        ),
    ]
