# Generated by Django 5.2 on 2025-11-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='documento',
            #name='contenido_extraido',
            #field=models.TextField(blank=True, null=True),
        #),
        migrations.AlterField(
            model_name='plantilladocumento',
            name='tipo',
            field=models.CharField(choices=[('comunicado', 'Comunicado'), ('convocatoria', 'Convocatoria'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('memorando', 'Memorando'), ('nota_interna', 'Nota Interna'), ('nota_externa', 'Nota Externa')], max_length=50),
        ),
    ]
