# Generated by Django 5.2 on 2025-11-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_documento_contenido_extraido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido_extraido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
