# Generated by Django 5.2 on 2025-12-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_documento_ambito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='ambito',
        ),
    ]
