# Generated by Django 5.2 on 2025-07-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_alter_plantilladocumento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido_extraido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
