# Generated by Django 5.2 on 2025-12-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_remove_documento_ambito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilladocumento',
            name='tipo',
            field=models.CharField(choices=[('comunicado', 'Comunicado'), ('convocatoria', 'Convocatoria'), ('resolucion', 'Resolución'), ('informe', 'Informe'), ('memorando', 'Memorando'), ('nota', 'Nota')], max_length=50),
        ),
    ]
