# Generated by Django 5.2 on 2026-03-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_alter_plantilladocumento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_data',
            field=models.TextField(blank=True, help_text='Archivo en formato base64', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255, null=True),
        ),
    ]
