# Generated by Django 5.2 on 2026-03-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_documento_archivo_data_documento_archivo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='archivo_data',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='archivo_nombre',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo_redis_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
