# Generated by Django 5.2 on 2026-07-23 19:10

import documento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_remove_documento_archivo_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=documento.models.ruta_archivo),
        ),
    ]
