# Generated by Django 5.2 on 2026-05-02 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondencia_id', models.PositiveIntegerField(help_text='ID de la correspondencia (solo referencia)')),
                ('tipo_alerta', models.CharField(choices=[('respuesta_pendiente', 'Respuesta Pendiente'), ('respuesta_vencida', 'Respuesta Vencida'), ('seguimiento_pendiente', 'Seguimiento Pendiente'), ('seguimiento_vencido', 'Seguimiento Vencido')], max_length=25)),
                ('nivel_alerta', models.CharField(choices=[('preventiva', 'Preventiva'), ('critica', 'Crítica')], max_length=10)),
                ('fecha_vencimiento', models.DateTimeField(help_text='Fecha límite para respuesta/seguimiento')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('vista', models.BooleanField(default=False)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_alerta'],
                'indexes': [models.Index(fields=['usuario_responsable', 'activa', 'vista'], name='alertas_ale_usuario_dd5bb2_idx'), models.Index(fields=['fecha_vencimiento'], name='alertas_ale_fecha_v_56f66f_idx')],
            },
        ),
    ]
