# Generated by Django 5.2 on 2026-05-03 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('correspondencia', '0020_delete_alertavencimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alertavencimiento',
            name='alertas_ale_usuario_dd5bb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='alertavencimiento',
            name='alertas_ale_fecha_v_56f66f_idx',
        ),
        migrations.RemoveField(
            model_name='alertavencimiento',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='alertavencimiento',
            name='correspondencia_id',
        ),
        migrations.RemoveField(
            model_name='alertavencimiento',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='alertavencimiento',
            name='correspondencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='correspondencia.correspondencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alertavencimiento',
            name='nivel_alerta',
            field=models.CharField(choices=[('informativa', 'Informativa'), ('preventiva', 'Preventiva'), ('critica', 'Crítica')], default='informativa', max_length=11),
        ),
        migrations.AlterField(
            model_name='alertavencimiento',
            name='tipo_alerta',
            field=models.CharField(choices=[('asignacion', 'Asignacion'), ('por_vencer', 'Por vencer'), ('vencido', 'Vencido')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='alertavencimiento',
            index=models.Index(fields=['usuario_responsable', 'vista'], name='alertas_ale_usuario_7768b9_idx'),
        ),
        migrations.AddIndex(
            model_name='alertavencimiento',
            index=models.Index(fields=['tipo_alerta'], name='alertas_ale_tipo_al_c18858_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertavencimiento',
            constraint=models.UniqueConstraint(fields=('correspondencia', 'usuario_responsable', 'tipo_alerta'), name='unique_alerta_correspondencia_usuario_tipo'),
        ),
    ]
