# Generated by Django 5.2 on 2026-05-03 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_remove_alertavencimiento_alertas_ale_usuario_dd5bb2_idx_and_more'),
        ('correspondencia', '0020_delete_alertavencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertavencimiento',
            name='correspondencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='correspondencia.correspondencia'),
        ),
    ]
