# Generated by Django 5.2 on 2026-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_alter_alertavencimiento_correspondencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertavencimiento',
            name='tipo_alerta',
            field=models.CharField(choices=[('por_vencer', 'Por vencer'), ('vencido', 'Vencido')], max_length=25),
        ),
    ]
