# Generated by Django 5.2 on 2026-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='secund_last_name',
            new_name='second_last_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='secund_name',
            new_name='second_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
