# Generated by Django 5.2 on 2025-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secund_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secund_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
