# Generated by Django 5.2 on 2026-05-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_secund_last_name_customuser_second_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alertas_activas',
            field=models.BooleanField(default=True, help_text='Activar/desactivar alertas de vencimiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dias_maximo_respuesta',
            field=models.PositiveIntegerField(default=3, help_text='Días máximos para responder una nota recibida'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dias_maximo_seguimiento',
            field=models.PositiveIntegerField(default=7, help_text='Días máximos para seguimiento de documentos enviados'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='horas_alerta_preventiva',
            field=models.PositiveIntegerField(default=24, help_text='Horas antes del vencimiento para recibir alerta'),
        ),
    ]
