# Generated by Django 5.2 on 2025-08-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_customuser_secund_last_name_customuser_secund_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
