# Generated by Django 5.2 on 2025-08-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_delete_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
