# Generated by Django 5.2 on 2026-05-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_add_alertas_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alertas_activas',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dias_maximo_respuesta',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dias_maximo_seguimiento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='horas_alerta_preventiva',
        ),
    ]
