# Generated by Django 5.2 on 2025-08-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_customuser_celular_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
