# Generated by Django 5.2 on 2025-08-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_customuser_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='responsable',
        ),
    ]
